version: "3"

services:
  app:
    container_name: docker-app
    build: .
    command: npm start
    ports: 
      - "3100:3100"
    volumes:
      - .:/usr/app
    environment: 
      - NODE_ENV=dev
      - PORT=3100
    links:
      - mongo
  mongo: 
    container_name: mongoserver
    image: mongo
    ports:
      - "27017:27017"